name: Deploy React project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm i --legacy-peer-deps
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload build to S3
        run: |
          aws s3 sync . s3://sadaf-test-bucket/ --recursive

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E8O9F1DMQZ2LY --paths "/*"
